# grid data 
data_dir: ../data/grid-data/

# grid name
grid:
    name: ACTIVSg200 

# tables (most likely leave these alone)
tables:
    actuals_start: 2007-01-01 00:00:00
    actuals_end: 2007-12-31 23:55:00
    scenarios_start: 2008-01-01 00:00:00 
    scenarios_end: 2013-12-31 23:55:00 

penetration: 

# scenarios 
scenario:
    start: 2007-07-01 00:00:00
    end: 2007-07-01 00:15:00 
    sampling_method: monte carlo 
    n_scenarios: 3 
    n_periods: 2 

# output dir for actuals, scenarios, and weights
output_dir: ./ 
